import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./components/footer";
import { Navbar } from "./components/navbar";

const albertSans = localFont({
  src: "./fonts/albert-sans-v1-latin-regular.woff2",
  variable: "--font-albert-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${albertSans.variable} min-h-screen antialiased bg-[#F5F5FF]`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
